### ISSUE TITLE
Need to re-pair after power off the TV

### ISSUE THREAD

**Issue by pablolassalle** [eclair4151/SmartCrypto#10]
HI @eclair4151,

I have an issue with my tv (J5500), I am able to get the token and Id session, and the work, I can send commands to the TV, but when I turn off and then ON the TV, I need to re-pair the TV again because TV seems not to receive any command.

**Comment by eclair4151** [comment]
Unfortunately i don't have a TV with this version to test on anymore so i can be much help. Some other people had reported that, but i havent found a solution. Try this guy out
https://github.com/kdschlosser/samsungctl

**Comment by pablolassalle** [comment]
Thank for your quick reply. I will try with him.
