### ISSUE TITLE
Pin NOT on TV

### ISSUE THREAD

**Issue by brayStorm** [eclair4151/SmartCrypto#11]
Is there any way to proceed from this point?

**Comment by eclair4151** [comment]
What model number is your tv?

**Comment by brayStorm** [comment]
UN58H5203

**Comment by eclair4151** [comment]
can you post the output of the script. Does it show any error or just nothing happens on the TV? i dont have one of these TVs anymore so i am not really able to help debug that much

**Comment by brayStorm** [comment]
Nothing happens on the TV. Here's the output;

**Comment by brayStorm** [comment]
The output just shows;
Current state: stopped
Pin NOT on TV
Please enter pin from tv:

**Comment by estevez-dev** [comment]
I have the same issue.
Model: UE55H6203AK
No errors, just:
```
python3 ./smartcrypto.py 
Current state: stopped
Pin NOT on TV
Please enter pin from tv: 
```

**Comment by eclair4151** [comment]
Sorry :/ i dont have this TV anymore and have no way to help.

**Comment by Ramias1** [comment]
Same issue with J6200
