### ISSUE TITLE
Where to find token?

### ISSUE THREAD

**Issue by ybjlus** [eclair4151/SmartCrypto#12]
I have run the script and pin is accepted. But now how do I find my token? What line is it in?

**Comment by eclair4151** [comment]
ctx and session id should both be printed to the console after a successful pair. can you post your output

**Comment by ybjlus** [comment]
> ctx and session id should both be printed to the console after a successful pair. can you post your output

They ar this is my output:

dest_hash: 23cde2a75acc36887dcf51c4b5aba5e8b8a046c1
SKPrime: ff3dcac76432edca79ef4d8647989ba5b272912c
SKPrimeHash: e65658474bced2287ad2ebb69e70626b09033e4d
ctx: 8fb3c54dd7aa3782e5025350f9a9589c
Pin accepted :)

sessionId: 1
SessionID: 1
Authorization successfull :)

Attempting to send command to tv
ws://192.168.1.116:8000/socket.io/1/websocket/tfD442lvirIQhuPTAQKo

**Comment by ybjlus** [comment]
Your comment made it clear, I have got it working!

ctx:sessionid
8fb3c54dd7aa3782e5025350f9a9589c:1
