### ISSUE TITLE
Question on Rijndael

### ISSUE THREAD

**Issue by dcorsus** [eclair4151/SmartCrypto#3]
@eclair4151 @mckael @sectroyer

This is not an issue but a question. I'm porting this code to vb.net for my HA application. So far all code works and is checked against the PY implementation but I can't figure out this code

def applySamyGOKeyTransform(input):
    r = Rijndael(bytes.fromhex(keys.transKey))
    return r.encrypt(input)

.net has AES and Rijdael but they return different results from what the PY code returns. All AES and SHA1 code in this PY project I figured out how to use with .NET but the above I can't figure out. Rijndael is supposed to be AES but you guys picked specifically an flavor of RIjndael. Any idea why? Any idea how this is different from AES? Specific setting?

**Comment by eclair4151** [comment]
Yes thats due to line 8 on this file
https://github.com/eclair4151/SmartCrypto/blob/master/PySmartCrypto/py3rijndael/constants.py

The number of rounds has manually been changed. you will need to find an open source version of  Rijndael for .net and go change that value

**Comment by dcorsus** [comment]
Thanks! Bummer, I thought I was done after a heavy weekend of coding :-(
