### ISSUE TITLE
Send command issue

### ISSUE THREAD

**Issue by Bercolly** [eclair4151/SmartCrypto#4]
Hi,
I ' ve tried to send command on a model J and the Tv seems not understanding the command.
The handshake part of the communication process works fine. 

Have you managed to send successfully a command andon which Tv model.
Thanks !

**Comment by ageorgios** [comment]
same here with JU6400

**Comment by andreas-bulling** [comment]
I can authenticate and send commands - I own a UE50J6250

**Comment by Bercolly** [comment]
@andreas-bulling 

Please can you show your code ?
Do you set a special value to the device-id ?
Regards

**Comment by andreas-bulling** [comment]
I am using the stock code - only modification is the IP address. At the very end of the authentication process the script sends a volume down event I believe.

**Comment by sniedetzki** [comment]
UN65J6300 here, first run of library failed to Client ACK.
Each run after this, authentication/pairing has been successful.
First handful of runs, the KEY_VOLDOWN worked as coded by default in library.

Now, no matter what key sent, nothing happens, pairing and all is still successful, but the TV ignores all commands.

Any help would be much appreciated, so excited to see this project, been waiting years to see the J series cracked.

**Comment by andreas-bulling** [comment]
@sniedetzki try this: https://github.com/kdschlosser/samsungctl

**Comment by sniedetzki** [comment]
@andreas-bulling thanks, have tried that though.
Was using that first, except there's a problem with that implementation of the library, won't authenticate past client hello. Keeps complaining when doing the unpack that "must be multiple of four".

There was also an issue where the device ID and app Id were not being passed to the encrypted remote implementation, the URL formed was blank for those two parameters, I hard coded those in that implementation from what I found they should be in the config.py, that's when I got to the error above.

Tried looking into it, but don't understand the protocol well enough to try and debug.

Does anyone know if there's a write-up of how the protocol works? If so I could look into helping fix the 65j6300 in the library.

**Comment by sniedetzki** [comment]
Just an update, I did a factory reset on the TV and now it is again responding to some of the KEYs sent to it, (VOLUME, POWER) but many still don't respond (Source, Menu).

This time instead of authenticating each time, I modified the code to reuse the CTX and session ID like mentioned in the code.

Anybody know what the websocket should be returning and what it's field mean?

**Comment by Cmac2016** [comment]
Will this code work on a 2018 Q series?
I have been trying to get this code to run and cannot get thru all the errors that are happening for me.  think I am down to last one but am having issues resolving this error:
    import LogIt, LogItWithReturn
ModuleNotFoundError: No module named 'LogIt'

**Comment by eclair4151** [comment]
@Cmac2016 please raise this issue on the Samsungctl github page. This library is not for Q led tvs.
