### ISSUE TITLE
Not Working on 2017 Model

### ISSUE THREAD

**Issue by Cmac2016** [eclair4151/SmartCrypto#5]
I have a QN65Q6FNA.
I do not get a pin page on my display when I run the command "ws://10.0.0.243:8001/ws/app/CloudPINPage".

if I run this from the WS google extension I get:
{
    "data": {
        "clients": [
            {
                "attributes": {
                    "name": null
                },
                "connectTime": 1559090240610,
                "deviceName": "Smart Device",
                "id": "ac9d77c9-af62-4f6b-b366-14e6d58d99e5",
                "isHost": false
            }
        ],
        "id": "ac9d77c9-af62-4f6b-b366-14e6d58d99e5"
    },
    "event": "ms.channel.connect"
}

I have tried so many different Samsung control python scripts and cannot get anything to work.
Any help would be great.

**Comment by eclair4151** [comment]
you have a new TV. This lib is only for series H and J tvs. (You have a Q series)
This library should work for you: https://github.com/kdschlosser/samsungctl

**Comment by Cmac2016** [comment]
Thank you.
I will check out that link.
