### ISSUE TITLE
ImportError: No module named 'Crypto'

### ISSUE THREAD

**Issue by webdandy** [eclair4151/SmartCrypto#8]
Hi,
can I please get help while executing:

`python3 PySmartCrypto/smartcrypto.py
Traceback (most recent call last):
  File "PySmartCrypto/smartcrypto.py", line 2, in <module>
    import crypto
  File "/root/temp/SmartCrypto-master/temp/SmartCrypto/PySmartCrypto/crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'`

Any ideas how I can fix this?

**Comment by stevusprimus** [comment]
I installed some libs. I think 

> pip install pycrypto 

did the trick

**Comment by stevusprimus** [comment]
Now I get 
`AttributeError: module 'websocket' has no attribute 'create_connection'`
After installing websocket ... some ideas?

**Comment by stevusprimus** [comment]
Solved with
`pip install samsungtv[websocket]`
that will also install websocket-client-0.57.0
